### ISSUE TITLE
Form helper does not handle numbers for nested fields

### ISSUE THREAD

**Issue by white-monkey** [hanami/helpers#110]
Hi,

I ran into a small problem with version `1.0.0`. I'm not sure whether it is a bug or me trying to do something I shouldn't. I came up with the following MWE:

```ruby
require 'hanami-helpers'

include Hanami::Helpers

users = [ { user_id: 10 }, { user_id: 11 } ]

def params; {}; end

r = html.div do
  form_for :users, '#' do
    users.each_with_index do |a, i|
      fields_for i do
        hidden_field :user_id, value: a[:user_id]
        text_area :story
      end
    end
  end
end

puts r.to_s
```
It produces the following HTML code:
```html
<div>
<form action="#" method="POST" accept-charset="utf-8" id="users-form">
<input type="hidden" name="users[][user_id]" id="users-0-user-id" value="10">
<textarea name="users[0][story]" id="users-0-story"></textarea>
<input type="hidden" name="users[][user_id]" id="users-1-user-id" value="11">
<textarea name="users[1][story]" id="users-1-story"></textarea>
</form>
</div>
```
As you can see, the `name` of the `input type="hidden"` is incomplete, and Rack raises an exception when the form is submitted. I thought that maybe using an Integer caused a problem somehow, so I replaced `fields_for i do` by `fields_for i.to_s do` but the result is the same. Only if I append or prepend a non-numeric character do I get to see the expected result.

**Comment by mereghost** [comment]
Hi @white-monkey , sorry for the delay in checking this. Could you check if the same happens with other kinds of inputs (text_field tel_field) too?

**Comment by TiteiKo** [comment]
Hi,

Because we're supporting `fields_for_collection`, we have a side effect that is that you can't have a subfield named by a numeric key (so user[1], user[1][foo] or just 1). Most of the time, if you think about doing something like that, you in fact want to have an array of items in the end

```
# so not this
{
  users: {
    "0": { user_id: "10", story: "..." },
    "1": { user_id: "11", story: "..." }
  }
}

# but this
{
  users: [
    { user_id: "10", story: "..." },
    { user_id: "11", story: "..." }
  ]
}
```

To have your action parameters look like this:

```ruby
params do
  required(:users).each do
    schema do
      required(:user_id) { int? }
      required(:story)     { str? }
    end
  end
end
```

In a nutshell: this is an unavoidable side effect (in the current architecture of the code) of the really cool feature `fields_for_collection` which you should definitively be using in your example and that would solve your problem :)

If you want to avoid it, you just need to use an alphanumeric key (ie: n0 instead of 0)

**Comment by TiteiKo** [comment]
@white-monkey I'm closing in favor of https://github.com/hanami/helpers/issues/111
