### ISSUE TITLE
the selected attribute on the option tag is not set

### ISSUE THREAD

**Issue by sebastjan-hribar** [hanami/helpers#66]
Hi,

I'm using select helper and the selected attribute on the option tag is not automatically set. For example, when displaying an entity for edit and update.

I've setup a small bookshelf with book and author entities. It's minimalistic just to get the minimum required environment ready.

Hanami data:
hanami,       '0.7.2'
hanami-model, '~> 0.5' 
hanami-helpers (~> 0.3)

Sample app: https://github.com/sebastjan-hribar/hanami-bookshelf

This is the html from inspecting page:

```
<h2>Edit book</h2>

<form action="/books/1" method="POST" accept-charset="utf-8" id="book-form">
<input type="hidden" name="_method" value="PATCH">
<div class="input">
<label for="book-title">Title</label>
<input type="text" name="book[title]" id="book-title" value="Test Book">
</div>
<div class="input">
<label for="book-author">Author</label>
<select name="book[author]" id="book-author">
<option value="1">Best Author</option>
<option value="2">Second Best Author</option>
</select>
</div>
<div class="controls">
<button type="submit">Update Book</button>
</div>
</form>
```

I've similar problems in my other app, I've setup this one just for this select problem.

Please let me know if I should add further information.

regards,
Sebastjan

**Comment by jodosha** [comment]
@sebastjan-hribar Thanks for reporting this problem.

I've cloned your demo app (thanks for that 🙏 ). It can't work, because the framework only selects an `<option>` tag in case of a HTTP param has a value that applies. This is useful in case of failing form submission: you want to render the form again, but won't loose the input that the user typed.

We should expand `select` with a new option to cover your case.

```erb
select :author, authors, selected: book.id
```

Then this check should be expanded accordingly: https://github.com/hanami/helpers/blob/4e91ee6fe1aa1096fa2484f90d159ef283433b21/lib/hanami/helpers/form_helper/form_builder.rb#L779

WDYT? Is it something that you want to implement? Thanks!

**Comment by sebastjan-hribar** [comment]
@jodosha I'm sorry for my late reply.

Thank you for the feedback.

`select :author, authors, selected: book.id` is something I had in mind for this scenario.

I'd be interested in trying to implement this, however I'm not confident I can do as good a job and as fast as an experienced person. But I have to start somewhere and sometime, right? :smile: 
Let me know if you would like to entrust this to someone else, or I should have a go at it.

On a second note:
I've pushed the updated test app to master where I've added a spec for the prompt option. The spec fails and also if I visit the page manually, the prompt is not there.

Before opening another issue, could you have a look at the [template](https://github.com/sebastjan-hribar/hanami-bookshelf/blob/master/apps/web/templates/books/new.html.erb#L12)
and the [spec](https://github.com/sebastjan-hribar/hanami-bookshelf/blob/master/spec/web/features/create_book_spec.rb#L9) to see I'm not making mistakes in my code.

regards,
Sebastjan

**Comment by jodosha** [comment]
@sebastjan-hribar I trust you.

There are plenty of tests here: https://github.com/hanami/helpers/blob/4e91ee6fe1aa1096fa2484f90d159ef283433b21/test/form_helper_test.rb#L1135, just add another one to cover this case and make it to pass. 😉 

---

The `:prompt` option was introduced on [Mar 10](https://github.com/hanami/helpers/commit/dbf2d63dff1cd2ccac44aae7f3d45bc0a7b93872), but not released yet. In your project, you're using a stable version of `hanami-helpers`, that's why you ain't no support for it yet.

**Comment by sebastjan-hribar** [comment]
@jodosha can you look at this [gist](https://gist.github.com/sebastjan-hribar/1525d4626077c17f754c6ee8c9608fbf)? After forking and bundle install I ran rake test and get the error in the gist.
Also this one is strange: [L25](https://gist.github.com/sebastjan-hribar/1525d4626077c17f754c6ee8c9608fbf#file-rake_error-rb-L25)

**Comment by jodosha** [comment]
@sebastjan-hribar `master` branch is now clean (see https://github.com/hanami/helpers/commit/b534567a259d60edd648c992ba70044875e6a4fc), please go ahead with this fix. Sorry about the trouble.

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/helpers/pull/69
