### ISSUE TITLE
FormBuilder output doesn't result in minified HTML

### ISSUE THREAD

**Issue by vladdypwnz** [hanami/helpers#80]
Here's a snippet from the FormBuilder code I have on a site I was building:

``` ruby
= form_for :applicant, routes.employ_path do
    - label 'Contact Name', for: :name, class: 'label login-label'
    - p class: 'control' do
      - text_field :name, class: 'input'
    - label 'Your LinkedIn', for: :linkedin, class: 'label login-label'
    - p class: 'control' do
      - text_field :linkedin, class: 'input'
    - label 'Your GitHub', for: :github, class: 'label login-label'
```

As you can see below, the rest of the document is very neatly compressed into one line in production except for the FormBuilder HTML:

![doesnt-minify](https://cloud.githubusercontent.com/assets/841644/19185588/20c6cc14-8c37-11e6-9437-72209ee0bd33.png)

Why is this happening and is this something that is PR-worthy to address?

**Comment by cllns** [comment]
Looks like [this is happening here](https://github.com/hanami/helpers/blob/83e503078657aaec13d718534311be7074b2d509/lib/hanami/helpers/html_helper/html_builder.rb#L324). Rather than `.join(NEWLINE)` it could just be `.join`.

I personally prefer non-minified HTML, since I don't think the benefit of a _slightly_ smaller page size is worth the trouble. Regardless, we should probably be consistent. Is it minified by default, or did you change something to do that?

**Comment by jodosha** [comment]
@vladdypwnz Hi. How the markup before the form is generated?

**Comment by joneslee85** [comment]
@vladdypwnz  ping :)

**Comment by jodosha** [comment]
I'm closing this. @vladdypwnz If you want to continue the discussion, please reopen and comment. Thanks! 😄
